### ISSUE TITLE
LICENSE is missed

### ISSUE THREAD

**Issue by asl** [ablab/nerpa#5]
The LICENSE file for this project is missed. Also, it seems that some files were borrowed from some other projects with license headers stripped which is not acceptable, please put them back.

**Comment by azmtag** [comment]
Do we need a license for the external tools?  Anyway, rBAN is licensed under Creative Commons Attribution-NonCommercial-ShareAlike 4.0 International Public License, according to their paper

**Comment by asl** [comment]
External tools are fine as license is for source code / binary code. Though, attribution would be requires as far as I can see :)

Note that CC-NC is more strict in terms of the usage
